### ISSUE TITLE
[csic_irregular] Input files naming, conditions specification

### ISSUE THREAD

**Issue by alfonsotecnalia** [eurobench/eurobench_protocol#47]
The algorithm is working with the provided test data. However, inputs of the algorithms do not follow Eurobench specs. Appart from naming, two conditions are passed as params top the same call instead of two different calls.
I have not been able to add the issue to the repo because I do not have permissions.

**Comment by aremazeilles** [comment]
Yes, but this is due to the fact that the metric is a direct comparison of the two measures. 
So we consider it as if it was data of the same run (even it is not). 

For instance:

```
./run_pi_variability Variability_octave/tests/data/input/GaitParameters_exo.yaml Variability_octave/tests/data/input/GaitParameters_noExo.yaml output
```

We assume we will get file recorded for the condition with exo, and for the condition no_exo, but we treat it as if it was two gait parameter files recorded during the same run.

**Comment by aremazeilles** [comment]
Can this be closed?

**Comment by alfonsotecnalia** [comment]
yes
